name: Build
on:
  - push
  - pull_request

env:
  NAME: get-dmax-links

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [ windows, linux, darwin ]
        GOARCH: [ amd64, 386, arm, arm64 ]
        exclude:
          - GOOS: windows
            GOARCH: arm
          - GOOS: darwin
            GOARCH: 386
          - GOOS: darwin
            GOARCH: arm

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: go build -ldflags="-s -w" -o dist/$NAME-$GOOS-$GOARCH

      - name: Rename binaries (Windows)
        if: matrix.GOOS == 'windows'
        run: for x in dist/$NAME-windows-*; do mv $x $x.exe; done

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.NAME}}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{github.sha}}
          path: dist/*
          retention-days: 90

